In [2]:
# Importation des bibliothèques principales
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import warnings


warnings.filterwarnings(
    "ignore", category=DeprecationWarning
)

In [3]:
## Set option pandas

pd.set_option('display.max_rows',2000)
pd.set_option('display.max_columns',2000)
pd.set_option('display.float_format', lambda x: '%.6f' % x)
pd.set_option('display.max_colwidth', None)

Le statisticien de la maternité de Bourgogne nous a transmis un jeu de données contenant 60 000 observations et 100 variables ainsi que le dictionnaire permettant de faire la jointure avec les variables. Ces données sont déjà nettoyées et validées en grandes parties puisqu'elles servent à la production du rapport annuel des établissements.

In [4]:
# ### chargement de la base de donnée communiquer par le statisticien de la maternité de Bourgogne ainsi que le dicionnaire de variable associé et transformation au format adapté csv

data=pd.read_excel('../00_Data/Bourgogne20132023.xls', engine='xlrd')
data.to_csv('../00_Data/Bourgogne20132023.csv', index=False)

dico_var=pd.read_excel('../00_Data/Dictionnaire variables.xlsx', engine='openpyxl')
dico_var.to_csv('../00_Data/dico_var.csv', index=False)

In [93]:
data=pd.read_csv('../00_Data/Bourgogne20132023.csv', low_memory=False)
data.head()

,id_chain,id_acc,terme,poids_mere,taille_mere,parite,Dosecortico,sdecl,codepost,type_grossesse,Aide_procreation,allaitement_mat,AMP,code_cesa,ERCF_stade,type_extr_i,diagnostique_reg,la,age_m,rss_acc,dat_acc,annee,niveau,bmi,acc_hh,allait,anest_peri,avort_spon,cesa,cesa_avt,cholestase,chorio,cortico,dc_mat,dech,decl,diabete,eclamps,embo,episio,ercf_ht,ercf_pdt,extr_i,g_type,hdd,hellp,hpp,hrp,hta_chro,hta_gest,hydramn,hyst,img,liga,map,oligo,pma,preecl,present,procid,rciu,rpm12,rpm37,rupt_ut,tr_rea,tr_sg,ut_cica,tiu,gene,meconium,Parite_PMS,Anest_gene,Act_pres,creta,pph_hemo,Tampo_int,tabac,hosp_m_g,dsm_g,hosp_m_a,dsm_acc,dsm_post,dsm_tot,bilan,nbilan,sej18,nsej18,d_naiss,sexe,apgar5,pc,crib,pHa,poi_nais,percent_be,percent_bh,dbp,deces,det_resp,ecat_malf,inf_bac_e,intub,malf,neuro,surf,tr_sg_e,vcpap,vm,ecun,ischemie,hiv,lmpv,rop,eai,hosp,hosp_rea,hosp_neo,hosp_ped,hosp_kan,d_mat,d_rea,d_neo,d_hosp,Declenchement,Autre_debut_trav,indication_decl,Autre_indication_decl,precision_decl,Autre_precision_decl,duree_rup_h,apgar1,apgar10,ph_veineux,parite_cor,map_cor,bas_risque,hta_tot,vitalite,mod_acc,mp,morti_peri,CodePSL,cgr,nb_cgr,hpp_trans
0,1,1,39.900000,NaN,NaN,NaN,NaN,NaN,21220,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,210780110,28.000000,572188,2014-01-31,2014,2.200000,NaN,0,0,1,0,0,NaN,0,0,0,0,0,NaN,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1.000000,0,0.000000,0,0,0,0,1,2.000000,0,0,4.000000,6.000000,0,0,1,1,2014-01-31,2,NaN,NaN,NaN,NaN,3540.000000,0.000000,0.000000,0.000000,0,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,Risque,0,vivant,vb,0,0,NaN,NaN,NaN,0
1,1,1,41.600000,74.000000,178.000000,0.000000,NaN,0,21201,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,210012175,27.000000,266272,2015-01-04,2015,1.200000,23.400000,0,1,1,0,0,NaN,0,0,0,0,0,NaN,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.000000,0,0.000000,0,0,0,0,1,2.000000,0,0,6.000000,8.000000,0,0,0,0,2015-01-04,1,10.000000,36.500000,NaN,NaN,3920.000000,0.000000,0.000000,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Risque,0,vivant,vb,0,0,NaN,NaN,NaN,0
2,1,1,41.200000,62.000000,167.000000,2.000000,NaN,NaN,21000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,210011367,36.000000,7937,2017-10-01,2017,2.200000,22.200000,0,0,1,0,0,NaN,0,0,0,0,0,NaN,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1.000000,0,0.000000,0,0,0,0,1,1.000000,0,0,3.000000,4.000000,0,0,0,0,2017-10-01,1,10.000000,NaN,NaN,7.250000,3310.000000,0.000000,0.000000,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,Risque,0,vivant,vb,0,0,NaN,NaN,NaN,0
3,1,1,38.600000,43.000000,159.000000,0.000000,NaN,NaN,21700,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,210012175,35.000000,43383,2018-04-15,2018,1.200000,17.000000,0,1,1,0,0,NaN,0,0,0,0,0,NaN,0,0,0,0,0,0,2,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.000000,0,0.000000,0,0,0,0,0,0.000000,0,0,4.000000,4.000000,0,0,0,0,2018-04-15,2,10.000000,33.500000,NaN,NaN,2890.000000,0.000000,0.000000,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,Risque,0,vivant,extri,0,0,NaN,NaN,NaN,0
4,2,1,39.900000,NaN,NaN,NaN,NaN,NaN,21000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,210780110,30.000000,580593,2014-03-03,2014,2.200000,NaN,0,1,1,0,0,NaN,0,0,0,0,0,NaN,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1.000000,0,0.000000,0,0,0,0,2,5.000000,0,0,3.000000,8.000000,0,0,1,1,2014-03-03,1,NaN,NaN,NaN,NaN,2850.000000,0.000000,0.000000,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,Risque,0,vivant,vb,0,0,NaN,NaN,NaN,0

In [175]:
dico_var.sort_values('Variables ')

,Variables,Intitulé/modalités
11,AMP,"Aide médicale à la procréation (FIV, ICSI, TEC, insémination artificielle)"
71,Act_pres,Acte presentation\n0:Presentation cephalique\n1:Presentation du siege\n2:Grossesse multiple\n3:Cesarienne
9,Aide_procreation,Procréation : Non/Oui
70,Anest_gene,Anesthesie generale (0 : Non/1 : Oui)
125,Autre_debut_trav,Autre début travail
127,Autre_indication_decl,Autre Indication de déclenchement
129,Autre_precision_decl,Autre précision de déclenchement
150,CodePSL,Code du produit sanguin administré
124,Declenchement,Declenchement
6,Dosecortico,"Corticotherapie : dose cumulée : 0,12,24,36…...mg"
13,ERCF_stade,Etude du rythme cardiaque fœtal (C1 à C5)
156,HPPsev,HPP sévère (0 : Non/1 : Oui)
69,Parite_PMS,Parite du PMSI (0 : Non/1 : Oui)
74,Tampo_int,Tamponnement intra-utérin (0 : Non/1 : Oui)
23,acc_hh,Accouchement hors hopital (0 : Non/1 : Oui)
154,agclass,NaN
17,age_m,Age maternel calculé à partir de la date de naissance de la mére et la date d'accocuhement \nexprimé en année
24,allait,Allaitement (0 : Non/1 : Oui)
10,allaitement_mat,Initiation de l'allaitement maternel : Non/Oui
136,analgesie,Analgésie
25,anest_peri,Anesthesie peridurale (0 : Non/1 : Oui)
20,annee,Année de l'accouchement
131,apgar1,Apgar 1 min
132,apgar10,Apgar 10 min
88,apgar5,Apgar 5 min
149,arcf,Anomalie rythme cardiaque fœtale (0 : Non/1 : Oui)
26,avort_spon,avortement spontane (0 : Non/1 : Oui)
140,bas_risque,bas risque
82,bilan,Bilan au cours de la grossesse
22,bmi,"L'indice de masse corporelle (IMC, ou BMI en anglais) se calcule donc en divisant le poids par la taille au carré"
27,cesa,Cesarienne\n1 : Cesarienne Sans indication\n2 : Cesarienne programmee\n3:Cesarienne urgente\n4: Cesarienne Sans indication
28,cesa_avt,Césarienne avant travail : 1: Oui
151,cgr,Délai d'administration calculé entre la date d'administration et la date d'accouchement
29,cholestase,Cholestase gravidique (0 : Non/1 : Oui)
30,chorio,Chorioamniotite (0 : Non/1 : Oui)
155,classbmi,NaN
12,code_cesa,"Code césarienne : blanc, rouge, vert, orange"
31,cortico,Corticothérapie (0 : Non/1 : Oui)
72,creta,Placenta acreta (0 : Non/1 : Oui)
120,d_hosp,Durée de séjour d'hospitalisation
117,d_mat,Durée de séjour à la mat
86,d_naiss_enfants,Date de naissance de l'enfant
119,d_neo,Durée de séjour en néonat
118,d_rea,Durée de séjour en réa
19,dat_acc,Date d'accouchement
94,dbp,Dysplasie broncho pulmonaire (0 : Non/1 : Oui)
32,dc_mat,Deces maternel (0 : Non/1 : Oui)
95,deces,Deces (0 : Non/1 : Oui)
33,dechirure,Dechirures 3 et 4ème degré
34,declenché,Declenchement (1 : Oui)
122,delai_dn,Delai dernieres nouvelles
96,det_resp,Detresse respiratoire (0 : Non/1 : Oui)
35,diabete,Diabete\n0 : Non\n1: Diabete preexistant\n2:Diabete gestationnel
15,diagnostique_reg,les codes diagnostic CIM10 de la mère
121,ds_tot_e,Durée de séjour totale
79,dsm_acc,Duree sejour avant accouchement
77,dsm_g,Duree hosp. pendant la grossesse
80,dsm_post,Duree de sejour post partum de la mere
81,dsm_tot,Duree de sejour totale pdt la grossesse
130,duree_rup_h,Durée rupture des membranes (heure)
111,eai,Encéphalopathie anoxo ischemique (0 : Non/1 : Oui)
97,ecat_malf,Malformations (EUROCAT) (0 : Non/1 : Oui)
36,eclamps,Eclampsie (0 : Non/1 : Oui)
106,ecun,Enterocolite Ultra Necrosante (0 : Non/1 : Oui)
37,embo,Embolisation (0 : Non/1 : Oui)
38,episio,Episiotomie (0 : Non/1 : Oui)
39,ercf_ht,Anomalie rythme cardiaque hors travail (0 : Non/1 : Oui)
40,ercf_pdt,Anomalie rythme cardiaque pendant travail (0 : Non/1 : Oui)
41,extr_i,Extraction instrumentale\n1:Forceps\n2:Ventouse\n9:Extr. Instrumentale sans indication
42,g_type,Type de grossesse\n1:mono\n2:multiple
67,gene,Anesthesie generale (0 : Non/1 : Oui)
43,hdd,Hemorragie de la delivrance (0 : Non/1 : Oui)
44,hellp,Hellp syndrome (0 : Non/1 : Oui)
108,hiv,Hemorragie intra-ventriculaire (0 : Non/1 : Oui)
112,hosp,Hospitalisation (0 : Non/1 : Oui)
116,hosp_kan,Hospitalisation à l'unité de Kanguoro (0 : Non/1 : Oui)
78,hosp_m_a,Hospitalisation a l'accouchement (0 : Non/1 : Oui)
76,hosp_m_g,Hosp. pendant la grossesse (0 : Non/1 : Oui)
114,hosp_neo,Hospitalisation en néonatal (0 : Non/1 : Oui)
115,hosp_ped,Hospitalisation en pédiatrie (0 : Non/1 : Oui)
113,hosp_rea,Hospitalisation en réanimation (0 : Non/1 : Oui)
45,hpp,Hemorragie du post-partum (0 : Non/1 : Oui)
153,hpp_trans,HPP transfusée (0 : Non/1 : Oui)
46,hrp,Hematome retroplacentaire et/ou marginal (0 : Non/1 : Oui)
47,hta_chro,Hypertension arterielle chronique (0 : Non/1 : Oui)
48,hta_gest,Hypertension arterielle gravidique (0 : Non/1 : Oui)
141,hta_tot,HTA total (chronique + gravidique)
49,hydramn,Hydramnios (0 : Non/1 : Oui)
50,hyst,Hysterectomie (0 : Non/1 : Oui)
1,id_acc,"Identifiant accouchement: \nNombre de fois le même identifiant présente dans la base au cours des années de suivi (1,2,3)"
0,id_chain,Identifiant
51,img,Interruption medicale de grossesse (0 : Non/1 : Oui)
126,indication_decl,Indication de déclenchement
137,indications_cesa,Indication césarienne
98,inf_bac_e,Infection néonatale bactérienne (0 : Non/1 : Oui)
99,intub,Intubation en salle de naissance (0 : Non/1 : Oui)
107,ischemie,Ischemie cerebrale neonatal (0 : Non/1 : Oui)
16,la,Lieu d'accouchement (code finess)
52,liga,Ligature (0 : Non/1 : Oui)
109,lmpv,Leucomalacie periventriculaire (0 : Non/1 : Oui)
100,malf,Malformations (0 : Non/1 : Oui)
53,map,Menace d'accouchement premature (0 : Non/1 : Oui)
139,map_cor,Map corrigée
68,meconium,Liquide meconial (0 : Non/1 : Oui)
143,mod_acc,Mode d'accouchement\nvb:voie basse\nextri:extraction instrumentale\ncesa : césarienne
146,morti_neo,Mortalité néonatale (0 : Non/1 : Oui)
147,morti_neo_p,Mortalité néonatale précoce (0 : Non/1 : Oui)
148,morti_neo_t,Mortalité néonatale tardive (0 : Non/1 : Oui)
145,morti_peri,Mortalité périnatale (0 : Non/1 : Oui)
144,mp,mortalité périnatal cause neuro (0 : Non/1 : Oui)
152,nb_cgr,Nombre du culot sanguin
83,nbilan,Nb bilans au cours de la grossesse
101,neuro,Pathologie neurologique lourde (0 : Non/1 : Oui)
21,niveau,"Niveau de l'etablissement d'accouchement : \n1 : niveau 1, 1,2 : niveau 1a, 2 : niveau 2, 2,1 : niveau 2a, 2,2 : niveau 2b et niveau 3"
85,nsej18,Nb sejours < 18 SA
54,oligo,Oligoamnios (0 : Non/1 : Oui)
89,pHa,ph artériel
5,parite,Parité obstétricale : nombre d'enfants issues d'une grossesses antérieure vivants\nou mort-né : de 0 à 9
138,parite_cor,Parité corrigée
134,patho_gross,pathologie de grossesse
135,pathologies_acc,pathologie d'accouchement
91,percent,Percentile (Mamelle)
92,percent_be,"Percentile (BE)\n0 = ""Eutophiques""\n 1 = ""Hypotrophes""\n 2 = ""Hypotrophes""\n 3 = ""Macrosomes""\n 4 = ""Macrosomes"";"
93,percent_bh,"Percentile (BH)\n0 = ""Eutophiques""\n 1 = ""Hypotrophes""\n 2 = ""Hypotrophes""\n 3 = ""Macrosomes""\n 4 = ""Macrosomes"";"
133,ph_veineux,ph veineux
55,pma,Procréation médicalement assistée (0 : Non/1 : Oui)
90,poi_nais,poids à la naissance (g)
3,poids_mere,Poids de la mére (en kg)
73,pph_hemo,pph_hemo\n0:Non\n1:Non hémorragique\n2:Hémorragique
128,precision_decl,Précision de déclenchement
56,preecl,Preeclampsie (0 : Non/1 : Oui)
57,present,Presentation à l'accouchement (0 : Non/1 : Oui)
58,procid,Procidence du cordon (0 : Non/1 : Oui)
59,rciu,Suspicion d'hypotrophie fœtale (0 : Non/1 : Oui)
123,retransfert,Retransfert (0 : Non/1 : Oui)
110,rop,Retinopathie de la prematurite (0 : Non/1 : Oui)
60,rpm12,Rupture précoce des membranes\n0:Non\n1:<24h\n2:>24h
61,rpm37,Rupture prolongee des membranes (0 : Non/1 : Oui)
18,rss_acc,code PMSI du séjour de la mère
62,rupt_ut,Rupture utérine (0 : Non/1 : Oui)
7,sdecl,Declenchement : Non/Oui
84,sej18,Sejours < 18 SA
87,sexe,Sexe de l'enfant\n1:M\n2:F
102,surf,Surfactant (0 : Non/1 : Oui)
75,tabac,Tabac (0 : Non/1 : Oui)
4,taille_mere,Taille de la mére (en cm)
2,terme,Terme à l'accouchement en semaine d aménorrhée (SA)
66,tiu,transfert in utero (0 : Non/1 : Oui)
63,tr_rea,Transfert en réa (0 : Non/1 : Oui)
64,tr_sg,Transfusion (0 : Non/1 : Oui)
103,tr_sg_e,Transfusion sanguine et produits sanguins labiles (0 : Non/1 : Oui)
14,type_extr_i,Type d'éxtraction instrumentale
8,type_grossesse,Type de grossesse
65,ut_cica,Uterus cicatriciel (0 : Non/1 : Oui)
104,vcpap,Ventilation nasale (0 : Non/1 : Oui)
142,vitalite,Vitalité
105,vm,Ventilation invasive (0 : Non/1 : Oui)

In [ ]:
data.columns.to_list()

In [173]:
data['Dosecortico'].value_counts()

Dosecortico
24.000000    3102
12.000000     402
0.000000       69
48.000000      48
36.000000      13
60.000000       2
84.000000       1
17.000000       1
72.000000       1
Name: count, dtype: int64

In [56]:
# Dictionnaire des variables HPP classées par moment clinique
variables_par_moment = {
    "avant_entree_maternite": {
        "Caractéristiques_maternelles": [
            "age_m", "bmi", "poids_mere", "taille_mere", "annee"
        ],
        "Habitudes_de_vie": [
            "tabac"
        ],
        "Antécédents_obstétricaux": [
            "parite", "parite_cor", "avort_spon", "ut_cica"
        ],
        "Contexte_de_conception": [
            "AMP", "Aide_procreation", "pma"
        ],
        "Pathologies_chroniques_ou_prenatales": [
            "diabete", "hta_chro", "hta_gest", "cholestase", "preecl",
            "patho_gross", "map", "map_cor", "rciu", "hydramn", "oligo",
            "creta"  # placenta accreta diagnostiqué anténatalement
        ],
        "Suivi_médical": [
            "bilan", "nbilan", "classbmi", "agclass"
        ],
        "Type_de_grossesse": [
            "g_type", "type_grossesse"
        ]
    },

    "admission_avant_travail": {
        "Situation_à_l_arrivée": [
            "Declenchement", "sdecl", "declenché",
            "indication_decl", "precision_decl",
            "autre_indication_decl", "autre_precision_decl"
        ],
        "Paramètres_cliniques": [
            "hta_tot", "terme", "present", "Act_pres",
            "rpm12", "rpm37", "duree_rup_h"
        ],
        "Conditions_obstétricales": [
            "placenta_previa", "chorio", "hrp",
            "meconium", "bas_risque"
        ],
        "Admission_hospitalière": [
            "hosp_m_a", "hosp_m_g", "hosp"
        ],
        "Examens_admission": [
            "ercf_ht", "amp_cor", "dsm_acc"
        ],
        "Variables_techniques_disponibles": [
            "niveau", "la", "id_acc", "id_chain", "diagnostique_reg"
        ]
    },

    "pendant_ou_apres_accouchement": {
        "Actes_obstétricaux": [
            "cesa", "cesa_avt", "code_cesa", "indications_cesa",
            "analgesie", "anest_peri", "gene", "anest_gene",
            "episio", "extr_i", "type_extr_i", "mod_acc", "rupt_ut", "procid"
        ],
        "Complications_travail_postpartum": [
            "hpp", "hpp_trans", "HPPsev", "tr_sg", "tr_sg_e", "nb_cgr",
            "CodePSL", "tampo_int", "embo", "hyst", "liga",
            "dechirure", "hrp", "chorio", "pph_hemo"
        ],
        "Soins_néonataux": [
            "apgar1", "apgar5", "apgar10", "poi_nais", "pHa", "ph_veineux",
            "percent", "percent_be", "percent_bh", "neuro", "eai", "ecun",
            "dbp", "hiv", "ischemie", "lmpv", "inf_bac_e", "det_resp",
            "surf", "vcpap", "vm", "intub", "rop"
        ],
        "Hospitalisations_postpartum": [
            "hosp_neo", "hosp_ped", "hosp_rea", "d_mat", "d_post",
            "dsm_post", "ds_tot_e", "dsm_tot"
        ],
        "Issues_maternelles": [
            "dc_mat", "deces", "morti_neo", "morti_neo_p", "morti_neo_t",
            "morti_peri", "mp", "retransfert", "tr_rea", "delai_dn",
            "d_naiss_enfants", "vitalite", "allait", "allaitement_mat"
        ]
    }
}

In [103]:
features_avt_acc=[]

for keys in variables_par_moment:
    if keys not in ['pendant_ou_apres_accouchement'] :
        for keys2 in variables_par_moment[keys]:
            for features in variables_par_moment[keys][keys2]:
                if features in [col for col in data.columns]:
                    features_avt_acc.append(features)

In [102]:
df_pred=data[features_avt_acc]
df_pred.head()

,age_m,bmi,poids_mere,taille_mere,annee,tabac,parite,parite_cor,avort_spon,ut_cica,AMP,Aide_procreation,pma,diabete,hta_chro,hta_gest,cholestase,preecl,map,map_cor,rciu,hydramn,oligo,creta,bilan,nbilan,g_type,type_grossesse,Declenchement,sdecl,indication_decl,precision_decl,hta_tot,terme,present,Act_pres,rpm12,rpm37,duree_rup_h,chorio,hrp,meconium,bas_risque,hosp_m_a,hosp_m_g,hosp,ercf_ht,dsm_acc,niveau,la,id_acc,id_chain,diagnostique_reg
0,28.000000,NaN,NaN,NaN,2014,0,NaN,NaN,0,0,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,NaN,NaN,NaN,NaN,NaN,0,39.900000,0,0.000000,0,0,NaN,0,0,1,Risque,0,1,0.000000,0,0,2.200000,210780110,1,1,NaN
1,27.000000,23.400000,74.000000,178.000000,2015,0,0.000000,NaN,0,0,NaN,NaN,0,0,0,0,0,0,1,1,0,0,0,0,0,0,1,NaN,NaN,0,NaN,NaN,0,41.600000,0,0.000000,0,0,NaN,0,0,0,Risque,0,1,0.000000,0,0,1.200000,210012175,1,1,NaN
2,36.000000,22.200000,62.000000,167.000000,2017,0,2.000000,NaN,0,0,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,NaN,NaN,NaN,NaN,NaN,0,41.200000,0,0.000000,0,0,NaN,0,0,0,Risque,0,1,0.000000,0,0,2.200000,210011367,1,1,NaN
3,35.000000,17.000000,43.000000,159.000000,2018,0,0.000000,NaN,0,0,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,NaN,NaN,NaN,NaN,NaN,0,38.600000,0,0.000000,0,0,NaN,0,0,0,Risque,0,0,0.000000,0,0,1.200000,210012175,1,1,NaN
4,30.000000,NaN,NaN,NaN,2014,0,NaN,NaN,0,0,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,NaN,NaN,NaN,NaN,NaN,0,39.900000,0,0.000000,0,0,NaN,0,0,0,Risque,0,2,0.000000,0,0,2.200000,210780110,1,2,NaN

In [ ]:
poids_mere, taille_mere, bmi, age_m, parite, Aide_procreation, AMP, pma, ut_cica, tabac, hta_chro, hta_gest, preecl, diabete, hydramn, oligo, rciu, map.

In [ ]:
variables_avant_salle = [
 'age_m', 'bmi', 'poids_mere', 'taille_mere', 'annee',
 'tabac', 'parite', 'parite_cor', 'ut_cica',
 'AMP', 'Aide_procreation', 'pma',
 'diabete', 'hta_chro', 'cholestase', 'preecl',
 'map', 'map_cor', 'rciu', 'hydramn', 'oligo', 'creta',
 'bilan', 'nbilan', 'g_type', 'type_grossesse', 'terme', 'present', 'Act_pres'
]

In [132]:
df_pred=data[variables_avant_salle]

In [133]:
df_pred.describe(include='all').T.sort_values('count')

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
parite_cor,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AMP,1155,5,FIV,353,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Aide_procreation,21585.000000,NaN,NaN,NaN,0.058467,0.234629,0.000000,0.000000,0.000000,0.000000,1.000000
type_grossesse,21589,7,monofoetale,21111,NaN,NaN,NaN,NaN,NaN,NaN,NaN
bmi,53061.000000,NaN,NaN,NaN,24.425610,5.206418,12.000000,20.700000,23.200000,27.000000,50.000000
taille_mere,53227.000000,NaN,NaN,NaN,164.291826,6.255011,109.000000,160.000000,165.000000,169.000000,190.000000
poids_mere,53403.000000,NaN,NaN,NaN,66.338483,15.824712,27.000000,55.000000,63.000000,73.000000,200.000000
parite,54214.000000,NaN,NaN,NaN,1.002951,1.140132,0.000000,0.000000,1.000000,2.000000,23.000000
Act_pres,65233.000000,NaN,NaN,NaN,0.574357,1.160062,0.000000,0.000000,0.000000,0.000000,3.000000
age_m,65534.000000,NaN,NaN,NaN,30.247902,5.193347,12.000000,27.000000,30.000000,34.000000,62.000000
avort_spon,65535.000000,NaN,NaN,NaN,0.002716,0.052046,0.000000,0.000000,0.000000,0.000000,1.000000
terme,65535.000000,NaN,NaN,NaN,39.264601,2.541292,22.000000,38.600000,39.900000,40.600000,43.000000
hta_tot,65535.000000,NaN,NaN,NaN,0.023270,0.150761,0.000000,0.000000,0.000000,0.000000,1.000000
annee,65535.000000,NaN,NaN,NaN,2017.360174,3.241942,2013.000000,2014.000000,2017.000000,2020.000000,2023.000000
g_type,65535.000000,NaN,NaN,NaN,1.023529,0.162463,1.000000,1.000000,1.000000,1.000000,9.000000
nbilan,65535.000000,NaN,NaN,NaN,0.149874,0.499549,0.000000,0.000000,0.000000,0.000000,16.000000
bilan,65535.000000,NaN,NaN,NaN,0.114717,0.318683,0.000000,0.000000,0.000000,0.000000,1.000000
creta,65535.000000,NaN,NaN,NaN,0.000671,0.025903,0.000000,0.000000,0.000000,0.000000,1.000000
oligo,65535.000000,NaN,NaN,NaN,0.026886,0.161753,0.000000,0.000000,0.000000,0.000000,1.000000
ut_cica,65535.000000,NaN,NaN,NaN,0.102907,0.303839,0.000000,0.000000,0.000000,0.000000,1.000000
hydramn,65535.000000,NaN,NaN,NaN,0.007492,0.086233,0.000000,0.000000,0.000000,0.000000,1.000000
map_cor,65535.000000,NaN,NaN,NaN,0.087297,0.282272,0.000000,0.000000,0.000000,0.000000,1.000000
map,65535.000000,NaN,NaN,NaN,0.087297,0.282272,0.000000,0.000000,0.000000,0.000000,1.000000
preecl,65535.000000,NaN,NaN,NaN,0.031159,0.208114,0.000000,0.000000,0.000000,0.000000,2.000000
present,65535.000000,NaN,NaN,NaN,0.053758,0.261157,0.000000,0.000000,0.000000,0.000000,3.000000
hta_chro,65535.000000,NaN,NaN,NaN,0.003647,0.060280,0.000000,0.000000,0.000000,0.000000,1.000000
diabete,65535.000000,NaN,NaN,NaN,0.274983,0.683632,0.000000,0.000000,0.000000,0.000000,2.000000
pma,65535.000000,NaN,NaN,NaN,0.027466,0.163439,0.000000,0.000000,0.000000,0.000000,1.000000
tabac,65535.000000,NaN,NaN,NaN,0.160189,0.366784,0.000000,0.000000,0.000000,0.000000,1.000000
rciu,65535.000000,NaN,NaN,NaN,0.041794,0.200121,0.000000,0.000000,0.000000,0.000000,1.000000
cholestase,65535.000000,NaN,NaN,NaN,0.010498,0.101922,0.000000,0.000000,0.000000,0.000000,1.000000

In [135]:
corr_matrix=df_pred.corr(method='spearman',numeric_only=True)

#
THRESOLD_CORR=0.3
high_corr = corr_matrix[corr_matrix.abs() > THRESOLD_CORR].stack().reset_index()
high_corr = high_corr[high_corr['level_0'] != high_corr['level_1']]  # Remove self-correlations
high_corr.columns = ['Variable 1', 'Variable 2', 'Correlation']

# Remove similar pairs (e.g., (A, B) and (B, A))
high_corr['sorted_vars'] = high_corr.apply(lambda row: tuple(sorted([row['Variable 1'], row['Variable 2']])), axis=1)
high_corr = high_corr.drop_duplicates(subset='sorted_vars').drop(columns='sorted_vars')


high_corr.sort_values('Correlation',ascending=False)

          Variable 1   Variable 2  Correlation
28               map      map_cor     1.000000
39             bilan       nbilan     0.998867
3                bmi   poids_mere     0.918223
17  Aide_procreation          pma     0.441606
24          hta_chro      hta_tot     0.391963
50           present     Act_pres     0.380427
21           diabete        bilan     0.359467
22           diabete       nbilan     0.357711
15           ut_cica     Act_pres     0.346048
1              age_m       parite     0.334622
6         poids_mere  taille_mere     0.309845
29               map        terme    -0.319819
32           map_cor        terme    -0.319819

In [136]:
feat_remove_corr=['map_cor','nbilan','poids_mere']

In [144]:
df_pred=df_pred.loc[:,[col for col in df_pred if  col not in feat_remove_corr]]
df_pred.head()

,age_m,bmi,taille_mere,annee,tabac,parite,parite_cor,avort_spon,ut_cica,AMP,Aide_procreation,pma,diabete,hta_chro,cholestase,preecl,map,rciu,hydramn,oligo,creta,bilan,g_type,type_grossesse,hta_tot,terme,present,Act_pres
0,28.000000,NaN,NaN,2014,0,NaN,NaN,0,0,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,1,NaN,0,39.900000,0,0.000000
1,27.000000,23.400000,178.000000,2015,0,0.000000,NaN,0,0,NaN,NaN,0,0,0,0,0,1,0,0,0,0,0,1,NaN,0,41.600000,0,0.000000
2,36.000000,22.200000,167.000000,2017,0,2.000000,NaN,0,0,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,1,NaN,0,41.200000,0,0.000000
3,35.000000,17.000000,159.000000,2018,0,0.000000,NaN,0,0,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,1,NaN,0,38.600000,0,0.000000
4,30.000000,NaN,NaN,2014,0,NaN,NaN,0,0,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,1,NaN,0,39.900000,0,0.000000

In [152]:
from scipy.stats import chi2_contingency
import numpy as np

def cramers_v(var1, var2):
    # Crée une table de contingence
    contingency_table = pd.crosstab(var1, var2)
    chi2, _, _, _ = chi2_contingency(contingency_table)
    n = contingency_table.sum().sum()
    phi2 = chi2 / n
    r, k = contingency_table.shape
    phi2corr = max(0, phi2 - ((k-1)*(r-1)) / (n-1))  # Correction de biais
    r_corr = r - ((r-1)**2) / (n-1)
    k_corr = k - ((k-1)**2) / (n-1)
    return np.sqrt(phi2corr / min(r_corr-1, k_corr-1))

In [154]:
# Calculer Cramér's V pour toutes les paires de colonnes
cramers_v_results = []

columns = df_pred.columns
for col1 in columns:
    for col2 in columns:
        if col1 != col2:  # Éviter de comparer une colonne avec elle-même
            contingency_table = pd.crosstab(df_pred[col1], df_pred[col2])
            if contingency_table.size > 0:  # Vérifier que la table de contingence n'est pas vide
                value = cramers_v(df_pred[col1], df_pred[col2])
                cramers_v_results.append({'Variable 1': col1, 'Variable 2': col2, 'Cramers V': value})

# Convertir les résultats en DataFrame
cramers_v_df = pd.DataFrame(cramers_v_results)

# Afficher les résultats triés par valeur de Cramér's V
cramers_v_df.sort_values(by='Cramers V', ascending=False, inplace=True)
cramers_v_df.head()

         Variable 1        Variable 2  Cramers V
567          g_type    type_grossesse   0.804981
593  type_grossesse            g_type   0.804981
413             map             terme   0.524135
639           terme               map   0.524135
269             pma  Aide_procreation   0.440831