In [33]:
import pandas as pd
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import plotly.io as pio

In [34]:
dataset=pd.read_csv('Speed+Dating+Data.csv',encoding='ISO-8859-1')
pd.options.display.max_columns = None
pd.options.display.max_rows = None

In [35]:
dataset.head(7)

,iid,id,gender,idg,condtn,wave,round,position,positin1,order,partner,pid,match,int_corr,samerace,age_o,race_o,pf_o_att,pf_o_sin,pf_o_int,pf_o_fun,pf_o_amb,pf_o_sha,dec_o,attr_o,sinc_o,intel_o,fun_o,amb_o,shar_o,like_o,prob_o,met_o,age,field,field_cd,undergra,mn_sat,tuition,race,imprace,imprelig,from,zipcode,income,goal,date,go_out,career,career_c,sports,tvsports,exercise,dining,museums,art,hiking,gaming,clubbing,reading,tv,theater,movies,concerts,music,shopping,yoga,exphappy,expnum,attr1_1,sinc1_1,intel1_1,fun1_1,amb1_1,shar1_1,attr4_1,sinc4_1,intel4_1,fun4_1,amb4_1,shar4_1,attr2_1,sinc2_1,intel2_1,fun2_1,amb2_1,shar2_1,attr3_1,sinc3_1,fun3_1,intel3_1,amb3_1,attr5_1,sinc5_1,intel5_1,fun5_1,amb5_1,dec,attr,sinc,intel,fun,amb,shar,like,prob,met,match_es,attr1_s,sinc1_s,intel1_s,fun1_s,amb1_s,shar1_s,attr3_s,sinc3_s,intel3_s,fun3_s,amb3_s,satis_2,length,numdat_2,attr7_2,sinc7_2,intel7_2,fun7_2,amb7_2,shar7_2,attr1_2,sinc1_2,intel1_2,fun1_2,amb1_2,shar1_2,attr4_2,sinc4_2,intel4_2,fun4_2,amb4_2,shar4_2,attr2_2,sinc2_2,intel2_2,fun2_2,amb2_2,shar2_2,attr3_2,sinc3_2,intel3_2,fun3_2,amb3_2,attr5_2,sinc5_2,intel5_2,fun5_2,amb5_2,you_call,them_cal,date_3,numdat_3,num_in_3,attr1_3,sinc1_3,intel1_3,fun1_3,amb1_3,shar1_3,attr7_3,sinc7_3,intel7_3,fun7_3,amb7_3,shar7_3,attr4_3,sinc4_3,intel4_3,fun4_3,amb4_3,shar4_3,attr2_3,sinc2_3,intel2_3,fun2_3,amb2_3,shar2_3,attr3_3,sinc3_3,intel3_3,fun3_3,amb3_3,attr5_3,sinc5_3,intel5_3,fun5_3,amb5_3
0,1,1.0,0,1,1,1,10,7,NaN,4,1,11.0,0,0.14,0,27.0,2.0,35.0,20.0,20.0,20.0,0.0,5.0,0,6.0,8.0,8.0,8.0,8.0,6.0,7.0,4.0,2.0,21.0,Law,1.0,NaN,NaN,NaN,4.0,2.0,4.0,Chicago,"60,521","69,487.00",2.0,7.0,1.0,lawyer,NaN,9.0,2.0,8.0,9.0,1.0,1.0,5.0,1.0,5.0,6.0,9.0,1.0,10.0,10.0,9.0,8.0,1.0,3.0,2.0,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,1,6.0,9.0,7.0,7.0,6.0,5.0,7.0,6.0,2.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,19.44,16.67,13.89,22.22,11.11,16.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
1,1,1.0,0,1,1,1,10,7,NaN,3,2,12.0,0,0.54,0,22.0,2.0,60.0,0.0,0.0,40.0,0.0,0.0,0,7.0,8.0,10.0,7.0,7.0,5.0,8.0,4.0,2.0,21.0,Law,1.0,NaN,NaN,NaN,4.0,2.0,4.0,Chicago,"60,521","69,487.00",2.0,7.0,1.0,lawyer,NaN,9.0,2.0,8.0,9.0,1.0,1.0,5.0,1.0,5.0,6.0,9.0,1.0,10.0,10.0,9.0,8.0,1.0,3.0,2.0,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,1,7.0,8.0,7.0,8.0,5.0,6.0,7.0,5.0,1.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,19.44,16.67,13.89,22.22,11.11,16.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
2,1,1.0,0,1,1,1,10,7,NaN,10,3,13.0,1,0.16,1,22.0,4.0,19.0,18.0,19.0,18.0,14.0,12.0,1,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,1.0,21.0,Law,1.0,NaN,NaN,NaN,4.0,2.0,4.0,Chicago,"60,521","69,487.00",2.0,7.0,1.0,lawyer,NaN,9.0,2.0,8.0,9.0,1.0,1.0,5.0,1.0,5.0,6.0,9.0,1.0,10.0,10.0,9.0,8.0,1.0,3.0,2.0,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,1,5.0,8.0,9.0,8.0,5.0,7.0,7.0,NaN,1.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,19.44,16.67,13.89,22.22,11.11,16.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
3,1,1.0,0,1,1,1,10,7,NaN,5,4,14.0,1,0.61,0,23.0,2.0,30.0,5.0,15.0,40.0,5.0,5.0,1,7.0,8.0,9.0,8.0,9.0,8.0,7.0,7.0,2.0,21.0,Law,1.0,NaN,NaN,NaN,4.0,2.0,4.0,Chicago,"60,521","69,487.00",2.0,7.0,1.0,lawyer,NaN,9.0,2.0,8.0,9.0,1.0,1.0,5.0,1.0,5.0,6.0,9.0,1.0,10.0,10.0,9.0,8.0,1.0,3.0,2.0,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,1,7.0,6.0,8.0,7.0,6.0,8.0,7.0,6.0,2.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,19.44,16.67,13.89,22.22,11.11,16.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
4,1,1.0,0,1,1,1,10,7,NaN,7,5,15.0,1,0.21,0,24.0,3.0,30.0,10.0,20.0,10.0,10.0,20.0,1,8.0,7.0,9.0,6.0,9.0,7.0,8.0,6.0,2.0,21.0,Law,1.0,NaN,NaN,NaN,4.0,2.0,4.0,Chicago,"60,521","69,487.00",2.0,7.0,1.0,lawyer,NaN,9.0,2.0,8.0,9.0,1.0,1.0,5.0,1.0,5.0,6.0,9.0,1.0,10.0,10.0,9.0,8.0,1.0,3.0,2.0,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,1,5.0,6.0,7.0,7.0,6.0,6.0,6.0,6.0,2.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,19.44,16.67,13.89,22.22,11.11,16.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
5,1,1.0,0,1,1,1,10,7,NaN,6,6,16.0,0,0.25,0,25.0,2.0,50.0,0.0,30.0,10.0,0.0,10.0,1,7.0,7.0,8.0,8.0,7.0,7.0,7.0,6.0,2.0,21.0,Law,1.0,NaN,NaN,NaN,4.0,2.0,4.0,Chicago,"60,521","69,487.00",2.0,7.0,1.0,lawyer,NaN,9.0,2.0,8.0,9.0,1.0,1.0,5.0,1.0,5.0,6.0,9.0,1.0,10.0,10.0,9.0,8.0,1.0,3.0,2.0,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,0,4.0,9.0,7.0,4.0,6.0,4.0,6.0,5.0,2.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,19.44,16.67,13.89,22.22,11.11,16.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
6,1,1.0,0,1,1,1,10,7,NaN,1,7,17.0,0,0.34,0,30.0,2.0,35.0,15.0,25.0,10.0,5.0,10.0,0,3.0,6.0,7.0,5.0,8.0,7.0,2.0,1.0,2.0,21.0,Law,1.0,NaN,NaN,NaN,4.0,2.0,4.0,Chicago,"60,521","69,487.00",2.0,7.0,1.0,lawyer,NaN,9.0,2.0,8.0,9.0,1.0,1.0,5.0,1.0,5.0,6.0,9.0,1.0,10.0,10.0,9.0,8.0,1.0,3.0,2.0,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,1,7.0,6.0,7.0,4.0,6.0,7.0,6.0,5.0,2.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,19.44,16.67,13.89,22.22,11.11,16.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN

In [36]:
dataset.describe()

,iid,id,gender,idg,condtn,wave,round,position,positin1,order,partner,pid,match,int_corr,samerace,age_o,race_o,pf_o_att,pf_o_sin,pf_o_int,pf_o_fun,pf_o_amb,pf_o_sha,dec_o,attr_o,sinc_o,intel_o,fun_o,amb_o,shar_o,like_o,prob_o,met_o,age,field_cd,race,imprace,imprelig,goal,date,go_out,career_c,sports,tvsports,exercise,dining,museums,art,hiking,gaming,clubbing,reading,tv,theater,movies,concerts,music,shopping,yoga,exphappy,expnum,attr1_1,sinc1_1,intel1_1,fun1_1,amb1_1,shar1_1,attr4_1,sinc4_1,intel4_1,fun4_1,amb4_1,shar4_1,attr2_1,sinc2_1,intel2_1,fun2_1,amb2_1,shar2_1,attr3_1,sinc3_1,fun3_1,intel3_1,amb3_1,attr5_1,sinc5_1,intel5_1,fun5_1,amb5_1,dec,attr,sinc,intel,fun,amb,shar,like,prob,met,match_es,attr1_s,sinc1_s,intel1_s,fun1_s,amb1_s,shar1_s,attr3_s,sinc3_s,intel3_s,fun3_s,amb3_s,satis_2,length,numdat_2,attr7_2,sinc7_2,intel7_2,fun7_2,amb7_2,shar7_2,attr1_2,sinc1_2,intel1_2,fun1_2,amb1_2,shar1_2,attr4_2,sinc4_2,intel4_2,fun4_2,amb4_2,shar4_2,attr2_2,sinc2_2,intel2_2,fun2_2,amb2_2,shar2_2,attr3_2,sinc3_2,intel3_2,fun3_2,amb3_2,attr5_2,sinc5_2,intel5_2,fun5_2,amb5_2,you_call,them_cal,date_3,numdat_3,num_in_3,attr1_3,sinc1_3,intel1_3,fun1_3,amb1_3,shar1_3,attr7_3,sinc7_3,intel7_3,fun7_3,amb7_3,shar7_3,attr4_3,sinc4_3,intel4_3,fun4_3,amb4_3,shar4_3,attr2_3,sinc2_3,intel2_3,fun2_3,amb2_3,shar2_3,attr3_3,sinc3_3,intel3_3,fun3_3,amb3_3,attr5_3,sinc5_3,intel5_3,fun5_3,amb5_3
count,8378.000000,8377.000000,8378.000000,8378.000000,8378.000000,8378.000000,8378.000000,8378.000000,6532.000000,8378.000000,8378.000000,8368.000000,8378.000000,8220.000000,8378.000000,8274.000000,8305.000000,8289.000000,8289.000000,8289.000000,8280.000000,8271.000000,8249.000000,8378.000000,8166.000000,8091.000000,8072.000000,8018.000000,7656.000000,7302.000000,8128.000000,8060.000000,7993.000000,8283.000000,8296.000000,8315.000000,8299.000000,8299.000000,8299.000000,8281.000000,8299.000000,8240.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8277.000000,1800.000000,8299.000000,8299.000000,8299.000000,8289.000000,8279.000000,8257.000000,6489.000000,6489.000000,6489.000000,6489.000000,6489.000000,6467.000000,8299.000000,8299.000000,8299.000000,8299.000000,8289.000000,8289.000000,8273.000000,8273.000000,8273.000000,8273.000000,8273.000000,4906.000000,4906.000000,4906.000000,4906.000000,4906.000000,8378.000000,8176.000000,8101.000000,8082.000000,8028.000000,7666.000000,7311.000000,8138.000000,8069.000000,8003.000000,7205.000000,4096.000000,4096.000000,4096.000000,4096.000000,4096.000000,4096.000000,4000.00000,4000.000000,4000.000000,4000.000000,4000.000000,7463.000000,7463.000000,7433.000000,1984.000000,1955.000000,1984.000000,1984.000000,1955.000000,1974.000000,7445.000000,7463.000000,7463.000000,7463.000000,7463.000000,7463.000000,5775.000000,5775.000000,5775.000000,5775.000000,5775.000000,5775.000000,5775.000000,5775.00000,5775.000000,5775.000000,5775.000000,5775.000000,7463.000000,7463.000000,7463.000000,7463.000000,7463.000000,4377.000000,4377.000000,4377.000000,4377.000000,4377.000000,3974.000000,3974.000000,3974.000000,1496.000000,668.000000,3974.000000,3974.000000,3974.000000,3974.000000,3974.000000,3974.000000,2016.000000,2016.000000,2016.000000,2016.000000,2016.000000,2016.000000,2959.000000,2959.000000,2959.000000,2959.000000,2959.000000,2959.000000,2959.000000,2959.000000,2959.000000,2959.000000,2959.000000,2016.000000,3974.000000,3974.000000,3974.000000,3974.000000,3974.000000,2016.000000,2016.000000,2016.000000,2016.000000,2016.000000
mean,283.675937,8.960248,0.500597,17.327166,1.828837,11.350919,16.872046,9.042731,9.295775,8.927668,8.963595,283.863767,0.164717,0.196010,0.395799,26.364999,2.756653,22.495347,17.396867,20.270759,17.459714,10.685375,11.845930,0.419551,6.190411,7.175256,7.369301,6.400599,6.778409,5.474870,6.134498,5.208251,1.960215,26.358928,7.662488,2.757186,3.784793,3.651645,2.122063,5.006762,2.158091,5.277791,6.425232,4.575491,6.245813,7.783829,6.985781,6.714544,5.737077,3.881191,5.745993,7.678515,5.304133,6.776118,7.919629,6.825401,7.851066,5.631281,4.339197,5.534131,5.570556,22.514632,17.396389,20.265613,17.457043,10.682539,11.845111,26.394360,11.071506,12.636308,15.566805,9.780089,11.014845,30.362192,13.273691,14.416891,18.422620,11.744499,11.854817,7.084733,8.294935,7.704460,8.403965,7.578388,6.941908,7.927232,8.284346,7.426213,7.617611,0.419909,6.189995,7.175164,7.368597,6.400598,6.777524,5.474559,6.134087,5.207523,0.948769,3.207814,20.791624,15.434255,17.243708,15.260869,11.144619,12.457925,7.21125,8.082000,8.257750,7.692500,7.589250,5.711510,1.843495,2.338087,32.819556,13.529923,15.293851,18.868448,7.286957,12.156028,26.217194,15.865084,17.813755,17.654765,9.913436,12.760263,26.806234,11.929177,12.103030,15.163810,9.342511,11.320866,29.344369,13.89823,13.958265,17.967233,11.909735,12.887976,7.125285,7.931529,8.238912,7.602171,7.486802,6.827964,7.394106,7.838702,7.279415,7.332191,0.780825,0.981631,0.376950,1.230615,0.934132,24.384524,16.588583,19.411346,16.233415,10.898075,12.699142,31.330357,15.654266,16.679563,16.418155,7.823909,12.207837,25.610341,10.751267,11.524839,14.276783,9.207503,11.253802,24.970936,10.923285,11.952687,14.959108,9.526191,11.966270,7.240312,8.093357,8.388777,7.658782,7.391545,6.810020,7.615079,7.932540,7.155258,7.048611
std,158.583367,5.491329,0.500029,10.940735,0.376673,5.995903,4.358458,5.514939,5.650199,5.477009,5.491068,158.584899,0.370947,0.303539,0.489051,3.563648,1.230689,12.569802,7.044003,6.782895,6.085526,6.126544,6.362746,0.493515,1.950305,1.740575,1.550501,1.954078,1.794080,2.156163,1.841258,2.129354,0.245925,3.566763,3.758935,1.230905,2.845708,2.805237,1.407181,1.444531,1.105246,3.309520,2.619024,2.801874,2.418858,1.754868,2.052232,2.263407,2.570207,2.620507,2.502218,2.006565,2.529135,2.235152,1.700927,2.156283,1.791827,2.608913,2.717612,1.734059,4.762569,12.587674,7.046700,6.783003,6.085239,6.124888,6.362154,16.297045,6.659233,6.717476,7.328256,6.998428,6.060150,16.249937,6.976775,6.263304,6.577929,6.886532,6.167314,1.395783,1.407460,1.564321,1.076608,1.778315,1.498653,1.627054,1.283657,1.779129,1.773094,0.493573,1.950169,1.740315,1.550453,1.953702,1.794055,2.156363,1.841285,2.129565,0.989889,2.444813,12.968524,6.915322,6.596420,5.356969,5.514028,5.921789,1.41545,1.455741,1.179317,1.626839,1.793136,1.820764,0.975662,0.631240,17.155270,7.977482,7.292868,8.535963,6.125187,8.241906,14.388694,6.658494,6.535894,6.129746,5.675550,6.651547,16.402836,6.401556,5.990607,7.290107,5.856329,6.296155,14.551171,6.17169,5.398621,6.100307,6.313281,5.615691,1.371390,1.503236,1.180280,1.548200,1.744634,1.411096,1.588145,1.280936,1.647478,1.521854,1.611694,1.382139,0.484683,1.294557,0.753902,13.712120,7.471537,6.124502,5.163777,5.900697,6.557041,17.551540,9.336288,7.880088,7.231325,6.100502,8.615985,17.477134,5.740351,6.004222,6.927869,6.385852,6.516178,17.007669,6.226283,7.010650,7.935509,6.403117,7.012067,1.576596,1.610309,1.459094,1.744670,1.961417,1.507341,1.504551,1.340868,1.672787,1.717988
min,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,5.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,-0.830000,0.000000,18.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,18.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,2.000000,2.000000,3.000000,2.000000,2.000000,1.000000,3.000000,2.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,0.000000,0.000000,1.000000,0.000000,0.000000,3.00000,1.000000,4.000000,3.000000,2.000000,1.000000,1.000000,1.000000,10.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,2.000000,2.000000,4.000000,1.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,2.000000,3.000000,2.000000,1.000000,2.000000,2.000000,4.000000,1.000000,1.000000
25%,154.000000,4.000000,0.000000,8.000000,2.000000,7.000000,14.000000,4.000000,4.000000,4.000000,4.000000,154.000000,0.000000,-0.020000,0.000000,24.000000,2.000000,15.000000,15.000000,17.390000,15.000000,5.000000,9.520000,0.000000,5.000000,6.000000,6.000000,5.000000,6.000000,4.000000,5.000000,4.000000,2.000000,24.000000,5.000000,2.000000,1.000000,1.000000,1.000000,4.000000,1.000000,2.000000,4.000000,2.000000,5.000000,7.000000,6.000000,5.000000,4.000000,2.000000,4.000000,7.000000,3.000000,5.000000,7.000000,5.000000,7.000000,4.000000,2.000000,5.000000,2.000000,15.000000,15.000000,17.390000,15.000000,5.000000,9.520000,10.000000,6.000000,8.000000,10.000000,5.000000,7.000000,20.000000,10.000000,10.000000,15.000000,6.000000,10.000000,6.000000,8.000000,7.000000,8.000000,7.000000,6.000000,7.000000,8.000000,6.000000,7.000000,0.000000,5.000000,6.000000,6.000000,5.000000,6.000000,4.000000,5.000000,4.000000,0.000000,2.000000,14.810000,10.000000,10.000000,10.000000,7.000000,9.000000,7.00000,7.000000,8.000000,7.000000,7.000000,5.000000,1.000000,2.000000,20.000000,10.000000,10.000000,10.000000,0.000000,5.000000,16.670000,10.000000,15.000000,15.000000,5.000000,10.000000,10.000000,8.000000,8.000000,9.000000,5.000000,7.000000,19.150000,10.00000,10.000000,15.000000,10.000000,10.000000,7.000000,7.000000,8.000000,7.000000,7.000000,6.000000,6.000000,7.000000,6.000000,6.000000,0.000000,0.000000,0.000000,1.000000,1.000000,15.220000,10.000000,16.670000,14.810000,5.000000,10.000000,20.000000,10.000000,10.000000,10.000000,0.000000,5.000000,10.000000,7.000000,7.000000,9.000000,5.000000,7.000000,10.000000,7.000000,7.000000,9.000000,6.000000,5.000000,7.000000,7.000000,8.000000,7.000000,6.000000,6.000000,7.000000,7.000000,6.000000,6.000000
50%,281.000000,8.000000,1.000000,16.000000,2.000000,11.000000,18.000000,8.000000,9.000000,8.000000,8.000000,281.000000,0.000000,0.210000,0.000000,26.000000,2.000000,20.000000,18.370000,20.000000,18.000000,10.000000,10.640000,0.000000,6.000000,7.000000,7.000000,7.000000,7.000000,6.000000,6.000000,5.000000,2.000000,26.000000,8.000000,2.000000,3.000000,3.000000,2.000000,5.000000,2.000000,6.000000,7.000000,4.000000,6.000000,8.000000,7.000000,7.000000,6.000000,3.000000,6.000000,8.000000,6.000000,7.000000,8.000000,7.000000,8.000000,6.000000,4.000000,6.000000,4.000000,20.000000,18.180000,20.000000,18.000000,10.000000,10.640000,25.000000,10.000000,10.000000,15.000000,10.000000,10.000000,25.000000,15.000000,15.000000,20.000000,10.000000,10.000000,7.000000,8.000000,8.000000,8.000000,8.000000,7.000000,8.000000,8.000000,8.000000,8.000000,0.000000,6.000000,7.000000,7.000000,7.000000,7.000000,6.000000,6.000000,5.000000,0.000000,3.000000,17.650000,15.790000,18.420000,15.910000,10.000000,12.500000,7.00000,8.000000,8.000000,8.000000,8.000000,6.000000,1.000000,2.000000,30.000000,10.000000,15.000000,20.000000,5.000000,10.000000,20.000000,16.670000,19.050000,18.370000,10.000000,13.000000,25.000000,10.000000,10.000000,15.000000,10.000000,10.000000,25.000000,15.00000,15.000000,18.520000,10.000000,13.950000,7.000000,8.000000,8.000000,8.000000,8.000000,7.000000,8.000000,8.000000,7.000000,7.000000,0.000000,1.000000,0.000000,1.000000,1.000000,20.000000,16.670000,20.000000,16.330000,10.000000,14.290000,25.000000,15.000000,18.000000,17.000000,10.000000,10.000000,20.000000,10.000000,10.000000,12.000000,9.000000,10.000000,20.000000,10.000000,10.000000,15.000000,10.000000,10.000000,7.000000,8.000000,8.000000,8.000000,8.000000,7.000000,8.000000,8.000000,7.000000,7.000000
75%,407.000000,13.000000,1.000000,26.000000,2.000000,15.000000,20.000000,13.000000,14.000000,13.000000,13.000000,408.000000,0.000000,0.430000,1.000000,28.000000,4.000000,25.000000,20.000000,23.810000,20.000000,15.000000,16.000000,1.000000,8.000000,8.000000,8.000000,8.000000,8.000000,7.000000,7.000000,7.000000,2.000000,28.000000,10.000000,4.000000,6.000000,6.000000,2.000000,6.000000,3.000000,7.000000,9.000000,7.000000,8.000000,9.000000,9.000000,8.000000,8.000000,6.000000,8.000000,9.000000,7.000000,9.000000,9.000000,8.000000,9.000000,8.000000,7.000000,7.000000,8.000000,25.000000,20.000000,23.810000,20.000000,15.000000,16.000000,35.000000,15.000000,16.000000,20.000000,15.000000,15.000000,40.000000,18.750000,20.000000,20.000000,15.000000,15.630000,8.000000,9.000000,9.000000,9.000000,9.000000,8.000000,9.000000,9.000000,9.000000,9.000000,1.000000,8.000000,8.000000,8.000000,8.000000,8.000000,7.000000,7.000000,7.000000,2.000000,4.000000,25.000000,20.000000,20.000000,20.000000,15.000000,16.280000,8.00000,9.000000,9.000000,9.000000,9.000000,7.000000,3.000000,3.000000,40.000000,20.000000,20.000000,24.000000,10.000000,20.000000,30.000000,20.000000,20.000000,20.000000,15.000000,16.670000,40.000000,15.000000,15.000000,20.000000,10.000000,15.000000,38.460000,19.23000,17.390000,20.000000,15.090000,16.515000,8.000000,9.000000,9.000000,9.000000,9.000000,8.000000,8.000000,9.000000,8.000000,8.000000,1.000000,1.000000,1.000000,1.000000,1.000000,30.000000,20.000000,20.000000,20.000000,15.000000,16.670000,40.000000,20.000000,20.000000,20.000000,10.000000,20.000000,37.000000,15.000000,15.000000,20.000000,10.000000,15.000000,35.000000,15.000000,15.000000,20.000000,10.000000,15.000000,8.000000,9.000000,9.000000,9.000000,9.000000,8.000000,9.000000,9.000000,8.000000,8.000000
max,552.000000,22.000000,1.000000,44.000000,2.000000,21.000000,22.000000,22.000000,22.000000,22.000000,22.000000,552.000000,1.000000,0.910000,1.000000,55.000000,6.000000,100.000000,60.000000,50.000000,50.000000,53.000000,30.000000,1.000000,10.500000,10.000000,10.000000,11.000000,10.000000,10.000000,10.000000,10.000000,8.000000,55.000000,18.000000,6.000000,10.000000,10.000000,6.000000,7.000000,7.000000,17.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,14.000000,10.000000,13.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,20.000000,100.000000,60.000000,50.000000,50.000000,53.000000,30.000000,95.000000,35.000000,35.000000,45.000000,50.000000,40.000000,100.000000,50.000000,40.000000,50.000000,50.000000,30.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,1.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,8.000000,18.000000,95.000000,50.000000,40.000000,40.000000,23.810000,30.000000,10.00000,10.000000,10.000000,10.000000,10.000000,10.000000,3.000000,3.000000,80.000000,40.000000,50.000000,50.000000,20.000000,40.000000,85.000000,50.000000,40.000000,50.000000,22.220000,35.000000,100.000000,35.000000,40.000000,50.000000,35.000000,40.000000,85.000000,40.00000,30.770000,40.000000,50.000000,30.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,21.000000,9.000000,1.000000,9.000000,4.000000,80.000000,65.000000,45.000000,30.000000,30.000000,55.000000,80.000000,60.000000,45.000000,40.000000,30.000000,55.000000,80.000000,40.000000,30.000000,30.000000,40.000000,45.000000,80.000000,50.000000,60.000000,40.000000,50.000000,45.000000,12.000000,12.000000,12.000000,12.000000,12.000000,10.000000,10.000000,10.000000,10.000000,10.000000

# Elimination des wave 6 à 9 pour les données concernées car systeme de notation incompatibles avec celui des autres waves . je check valeurs aberrantes et NA au fur et à mesure avec cette fonction pour plus de simplicité

In [37]:
def check_features(list_of_features):
  return display(
      'COUNT :',dataset.groupby('wave').count().loc[:,list_of_features].T,
      'MAX :',dataset.groupby('wave').max(numeric_only=True).loc[:,list_of_features].T,
      'MIN :',dataset.groupby('wave').min(numeric_only=True).loc[:,list_of_features].T,
      'NULL:',dataset[list_of_features].isnull().sum().reset_index().T
      )

# What are the least desirable attributes in a male partner? Does this differ for female partners?

In [38]:
check_features(['gender','attr1_1','sinc1_1','intel1_1','fun1_1','amb1_1','shar1_1'])

'COUNT :'

wave,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21
gender,200,608,200,648,190,50,512,200,800,162,882,392,180,720,684,96,280,72,450,84,968
attr1_1,200,592,180,648,190,45,512,200,800,162,882,392,160,702,684,96,280,72,450,84,968
sinc1_1,200,592,180,648,190,45,512,200,800,162,882,392,160,702,684,96,280,72,450,84,968
intel1_1,200,592,180,648,190,45,512,200,800,162,882,392,160,702,684,96,280,72,450,84,968
fun1_1,200,592,180,648,180,45,512,200,800,162,882,392,160,702,684,96,280,72,450,84,968
amb1_1,200,592,180,648,170,45,512,200,800,162,882,392,160,702,684,96,280,72,450,84,968
shar1_1,200,592,180,648,170,45,512,200,800,162,882,392,160,702,684,96,280,72,450,84,946

'MAX :'

wave,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21
gender,1.00,1.0,1.0,1.0,1.0,1.00,1.00,1.00,1.00,1.0,1.0,1.00,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
attr1_1,100.00,50.0,60.0,50.0,80.0,20.83,27.78,20.93,25.64,90.0,60.0,50.00,60.0,75.0,95.0,60.0,55.0,50.0,40.0,40.0,70.0
sinc1_1,25.00,35.0,25.0,32.0,40.0,22.73,23.08,23.81,23.81,30.0,40.0,47.00,60.0,30.0,30.0,30.0,40.0,30.0,26.0,30.0,30.0
intel1_1,35.00,50.0,45.0,50.0,35.0,20.00,22.73,23.26,23.81,30.0,45.0,42.86,30.0,30.0,40.0,40.0,50.0,25.0,30.0,40.0,30.0
fun1_1,40.00,30.0,30.0,24.0,35.0,20.83,27.78,22.50,23.81,25.0,25.0,25.00,25.0,50.0,35.0,20.0,45.0,30.0,30.0,20.0,30.0
amb1_1,18.18,25.0,53.0,20.0,20.0,20.00,19.57,20.41,20.59,20.0,25.0,20.00,20.0,30.0,20.0,20.0,18.0,20.0,20.0,20.0,16.0
shar1_1,22.22,20.0,20.0,30.0,20.0,19.57,19.57,17.39,23.81,25.0,25.0,22.00,30.0,25.0,30.0,30.0,30.0,25.0,20.0,20.0,30.0

'MIN :'

wave,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21
gender,0.00,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
attr1_1,9.09,10.0,5.0,10.0,10.0,6.67,8.33,9.52,7.50,10.0,0.0,5.0,2.0,5.0,8.0,5.0,10.0,10.0,10.0,10.0,10.0
sinc1_1,0.00,0.0,0.0,3.0,10.0,16.28,10.87,11.11,5.13,2.0,5.0,0.0,5.0,0.0,0.0,7.0,2.0,0.0,0.0,0.0,0.0
intel1_1,0.00,10.0,0.0,10.0,5.0,15.22,16.00,15.22,14.71,2.0,0.0,10.0,10.0,5.0,1.0,10.0,0.0,10.0,10.0,18.0,0.0
fun1_1,0.00,0.0,10.0,5.0,5.0,13.64,14.00,14.29,12.50,2.0,5.0,5.0,8.0,5.0,1.0,10.0,5.0,10.0,10.0,0.0,5.0
amb1_1,0.00,0.0,0.0,0.0,5.0,6.25,2.56,10.00,2.33,0.0,0.0,0.0,5.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0
shar1_1,0.00,0.0,0.0,0.0,0.0,12.50,2.78,2.27,2.38,2.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

'NULL:'

            0        1        2         3       4       5        6
index  gender  attr1_1  sinc1_1  intel1_1  fun1_1  amb1_1  shar1_1
0           0       79       79        79      89      99      121

In [39]:
dataset_wave=dataset.loc[(dataset['wave']<5) | (dataset['wave']>9) ,:].reset_index(drop=True)

In [40]:
df_least=dataset_wave.dropna(subset=['attr1_1','sinc1_1','intel1_1','fun1_1','amb1_1','shar1_1']).groupby('gender').mean(numeric_only=True).loc[:,'attr1_1':'shar1_1']
df_least.index=df_least.index.map({0:'Female',1:'Male'})
df_least.columns=df_least.columns.map({'attr1_1':'Attractiveness','sinc1_1':'Sincerity','intel1_1':'Intelligence','fun1_1':'Fun','amb1_1':'Ambition','shar1_1':'SharedInterest'})
df_least

,Attractiveness,Sincerity,Intelligence,Fun,Ambition,SharedInterest
gender,,,,,,
Female,18.549265,18.558811,21.523871,16.916549,11.973083,12.444538
Male,28.823711,16.209839,19.672864,17.730392,7.492669,10.240595

In [41]:
df_least2=dataset[['gender','shar1_1','sinc1_1','intel1_1','fun1_1','amb1_1','attr1_1']].dropna()
df_least2['gender']=df_least2['gender'].map({0:'Female',1:'Male'})
df_least2.columns=df_least2.columns.map({'gender':'gender','attr1_1':'Attractiveness','sinc1_1':'Sincerity','intel1_1':'Intelligence','fun1_1':'Fun','amb1_1':'Ambition','shar1_1':'SharedInterest'})
df_least2.head()

,gender,SharedInterest,Sincerity,Intelligence,Fun,Ambition,Attractiveness
0,Female,15.0,20.0,20.0,15.0,15.0,15.0
1,Female,15.0,20.0,20.0,15.0,15.0,15.0
2,Female,15.0,20.0,20.0,15.0,15.0,15.0
3,Female,15.0,20.0,20.0,15.0,15.0,15.0
4,Female,15.0,20.0,20.0,15.0,15.0,15.0

In [42]:
fig1=px.pie(df_least,values=df_least.iloc[0],names=df_least.columns,title="Fig 1 : Women's preferences by attributes",width=600,color_discrete_sequence = px.colors.qualitative.Pastel)
fig1.update_layout(
    title_x= 0.5,
    legend_title='Attributes :')
fig1.show()

In [43]:
fig2=px.pie(df_least,values=df_least.loc['Male'],names=df_least.columns,title="Fig 2 : Men's preferences by attributes",width=600,color_discrete_sequence = px.colors.qualitative.Pastel)
fig2.update_layout(
    title_x= 0.5,
    legend_title='Attributes :')
fig2.show()

In [44]:
fig3=px.box(df_least2,x=['SharedInterest','Sincerity','Intelligence','Fun','Ambition','Attractiveness'],color='gender',title='Fig 3 : Distribution of Preferences by gender',width=900,color_discrete_sequence = px.colors.qualitative.Pastel)
fig3.update_layout(
    title_x= 0.5,
    legend_title='Gender :',
    xaxis_title='Rating',
    yaxis_title=None)
fig3.show()

**Interpretation**

Figures 1 show us that the attributes women look for least in men are ambition and shared interests. Figure 2 shows us that ambition and shared interests are also the least desirable attributes in men for women. Moreover, figure 3 shows us that men's disinterest in these two attributes is even more pronounced. We also note that the distribution for all attributes is much more polarized for men towards a strong demand for women's attractiveness.

# How important do people think attractiveness is in potential mate selection vs. its real impact?

In [45]:
check_features(['gender','shar1_1','sinc1_1','intel1_1','fun1_1','amb1_1','attr1_1','dec','attr','sinc','intel','fun','amb','shar','attr7_2','sinc7_2','intel7_2','fun7_2','amb7_2','shar7_2'])

'COUNT :'

wave,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21
gender,200,608,200,648,190,50,512,200,800,162,882,392,180,720,684,96,280,72,450,84,968
shar1_1,200,592,180,648,170,45,512,200,800,162,882,392,160,702,684,96,280,72,450,84,946
sinc1_1,200,592,180,648,190,45,512,200,800,162,882,392,160,702,684,96,280,72,450,84,968
intel1_1,200,592,180,648,190,45,512,200,800,162,882,392,160,702,684,96,280,72,450,84,968
fun1_1,200,592,180,648,180,45,512,200,800,162,882,392,160,702,684,96,280,72,450,84,968
amb1_1,200,592,180,648,170,45,512,200,800,162,882,392,160,702,684,96,280,72,450,84,968
attr1_1,200,592,180,648,190,45,512,200,800,162,882,392,160,702,684,96,280,72,450,84,968
dec,200,608,200,648,190,50,512,200,800,162,882,392,180,720,684,96,280,72,450,84,968
attr,199,601,188,647,185,50,510,195,799,162,879,391,178,653,661,95,280,72,444,84,903
sinc,200,590,187,641,185,47,511,190,790,162,861,391,169,652,657,95,279,68,444,82,900
intel,200,586,186,647,185,45,507,191,789,160,860,381,178,645,652,95,278,66,444,84,903
fun,200,587,186,622,183,48,500,190,769,160,866,385,178,645,645,95,278,66,444,82,899
amb,198,574,179,580,183,47,451,175,761,146,819,374,162,628,585,93,278,68,425,78,862
shar,190,521,179,557,178,42,424,173,701,139,797,352,168,599,523,88,259,70,423,84,844
attr7_2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,391,50,140,54,405,64,880
sinc7_2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,372,50,130,54,405,64,880
intel7_2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,391,50,140,54,405,64,880
fun7_2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,391,50,140,54,405,64,880
amb7_2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,372,50,130,54,405,64,880
shar7_2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,391,50,130,54,405,64,880

'MAX :'

wave,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21
gender,1.00,1.0,1.0,1.0,1.0,1.00,1.00,1.00,1.00,1.0,1.0,1.00,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
shar1_1,22.22,20.0,20.0,30.0,20.0,19.57,19.57,17.39,23.81,25.0,25.0,22.00,30.0,25.0,30.0,30.0,30.0,25.0,20.0,20.0,30.0
sinc1_1,25.00,35.0,25.0,32.0,40.0,22.73,23.08,23.81,23.81,30.0,40.0,47.00,60.0,30.0,30.0,30.0,40.0,30.0,26.0,30.0,30.0
intel1_1,35.00,50.0,45.0,50.0,35.0,20.00,22.73,23.26,23.81,30.0,45.0,42.86,30.0,30.0,40.0,40.0,50.0,25.0,30.0,40.0,30.0
fun1_1,40.00,30.0,30.0,24.0,35.0,20.83,27.78,22.50,23.81,25.0,25.0,25.00,25.0,50.0,35.0,20.0,45.0,30.0,30.0,20.0,30.0
amb1_1,18.18,25.0,53.0,20.0,20.0,20.00,19.57,20.41,20.59,20.0,25.0,20.00,20.0,30.0,20.0,20.0,18.0,20.0,20.0,20.0,16.0
attr1_1,100.00,50.0,60.0,50.0,80.0,20.83,27.78,20.93,25.64,90.0,60.0,50.00,60.0,75.0,95.0,60.0,55.0,50.0,40.0,40.0,70.0
dec,1.00,1.0,1.0,1.0,1.0,1.00,1.00,1.00,1.00,1.0,1.0,1.00,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
attr,10.00,10.0,10.0,10.0,10.0,10.00,10.00,10.00,10.00,10.0,10.0,10.00,10.0,10.0,10.0,10.0,10.0,9.0,10.0,9.0,10.0
sinc,10.00,10.0,10.0,10.0,10.0,10.00,10.00,10.00,10.00,10.0,10.0,10.00,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0
intel,10.00,10.0,10.0,10.0,10.0,10.00,10.00,10.00,10.00,10.0,10.0,10.00,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0
fun,10.00,10.0,10.0,10.0,10.0,10.00,10.00,10.00,10.00,10.0,10.0,10.00,10.0,10.0,10.0,9.0,10.0,10.0,10.0,10.0,10.0
amb,10.00,10.0,10.0,10.0,10.0,10.00,10.00,10.00,10.00,10.0,10.0,10.00,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0
shar,10.00,10.0,10.0,10.0,10.0,10.00,10.00,10.00,10.00,10.0,10.0,10.00,10.0,10.0,10.0,10.0,10.0,9.0,10.0,8.0,10.0
attr7_2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,70.0,50.0,60.0,65.0,50.0,50.0,80.0
sinc7_2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.0,25.0,25.0,30.0,40.0,40.0,25.0
intel7_2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30.0,30.0,20.0,20.0,30.0,50.0,30.0
fun7_2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30.0,15.0,40.0,25.0,50.0,35.0,40.0
amb7_2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.0,15.0,17.0,15.0,20.0,10.0,20.0
shar7_2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.0,25.0,20.0,25.0,40.0,30.0,30.0

'MIN :'

wave,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21
gender,0.00,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
shar1_1,0.00,0.0,0.0,0.0,0.0,12.50,2.78,2.27,2.38,2.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
sinc1_1,0.00,0.0,0.0,3.0,10.0,16.28,10.87,11.11,5.13,2.0,5.0,0.0,5.0,0.0,0.0,7.0,2.0,0.0,0.0,0.0,0.0
intel1_1,0.00,10.0,0.0,10.0,5.0,15.22,16.00,15.22,14.71,2.0,0.0,10.0,10.0,5.0,1.0,10.0,0.0,10.0,10.0,18.0,0.0
fun1_1,0.00,0.0,10.0,5.0,5.0,13.64,14.00,14.29,12.50,2.0,5.0,5.0,8.0,5.0,1.0,10.0,5.0,10.0,10.0,0.0,5.0
amb1_1,0.00,0.0,0.0,0.0,5.0,6.25,2.56,10.00,2.33,0.0,0.0,0.0,5.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0
attr1_1,9.09,10.0,5.0,10.0,10.0,6.67,8.33,9.52,7.50,10.0,0.0,5.0,2.0,5.0,8.0,5.0,10.0,10.0,10.0,10.0,10.0
dec,0.00,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
attr,1.00,1.0,0.0,0.0,1.0,3.00,1.00,1.00,1.00,1.0,1.0,2.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
sinc,1.00,1.0,1.0,0.0,1.0,5.00,3.00,3.00,1.00,2.0,0.0,0.0,2.0,1.0,0.0,2.0,0.0,2.0,0.0,1.0,0.0
intel,1.00,1.0,0.0,0.0,2.0,4.00,3.00,3.00,1.00,4.0,1.0,2.0,3.0,2.0,0.0,4.0,3.0,3.0,0.0,3.0,0.0
fun,1.00,1.0,0.0,0.0,0.0,1.00,1.00,1.00,1.00,2.0,0.0,0.0,1.0,0.0,0.0,1.0,2.0,1.0,0.0,1.0,0.0
amb,1.00,1.0,1.0,0.0,0.0,4.00,2.00,2.00,1.00,1.0,1.0,1.0,2.0,2.0,0.0,2.0,2.0,1.0,0.0,4.0,0.0
shar,1.00,0.0,0.0,0.0,0.0,1.00,1.00,1.00,0.00,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
attr7_2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.0,15.0,10.0,10.0,10.0,10.0,10.0
sinc7_2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,10.0,5.0,0.0,0.0,0.0,0.0
intel7_2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,10.0,0.0,0.0,0.0,10.0,0.0
fun7_2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,5.0,10.0,0.0,5.0,0.0,0.0
amb7_2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,5.0,0.0,0.0,0.0,0.0,0.0
shar7_2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,10.0,0.0,0.0,0.0,0.0,0.0

'NULL:'

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
index,gender,shar1_1,sinc1_1,intel1_1,fun1_1,amb1_1,attr1_1,dec,attr,sinc,intel,fun,amb,shar,attr7_2,sinc7_2,intel7_2,fun7_2,amb7_2,shar7_2
0,0,121,79,79,89,99,79,0,202,277,296,350,712,1067,6394,6423,6394,6394,6423,6404

In [46]:
df_selected=pd.concat([dataset_wave.loc[dataset_wave['wave']>14,'attr1_1':'shar1_1'],dataset_wave.loc[dataset_wave['wave']>14,'attr7_2':'shar7_2']],axis=1).dropna().mean()
df1=df_selected['attr1_1':'shar1_1']
df2=df_selected['attr7_2':'shar7_2']
df1.name='Before'
df2.name='Review After'
df1.index=df1.index.map({'attr1_1':'Attractiveness','sinc1_1':'Sincerity','intel1_1':'Intelligence','fun1_1':'Fun','amb1_1':'Ambition','shar1_1':'SharedInterest'})
df2.index=df2.index.map({'attr7_2':'Attractiveness','sinc7_2':'Sincerity','intel7_2':'Intelligence','fun7_2':'Fun','amb7_2':'Ambition','shar7_2':'SharedInterest'})
df_selected=pd.concat([df1,df2],axis=1)
df_selected

                   Before  Review After
Attractiveness  23.442835     32.154165
Sincerity       17.209002     13.627005
Intelligence    20.034144     15.185204
Fun             18.332126     18.802380
Ambition         9.076048      7.369891
SharedInterest  11.771340     12.144853

In [47]:
df_selected1=pd.concat([dataset_wave.loc[dataset_wave['wave']>14,'attr1_1':'shar1_1'],dataset_wave.loc[dataset_wave['wave']>14,'attr7_2':'shar7_2']],axis=1).dropna()
df11=df_selected1.loc[:,'attr1_1':'shar1_1']
df21=df_selected1.loc[:,'attr7_2':'shar7_2']
df11['When']='Projected'
df21['When']='Revised'
df11.head()
df11.columns=df11.columns.map({'attr1_1':'Attractiveness','sinc1_1':'Sincerity','intel1_1':'Intelligence','fun1_1':'Fun','amb1_1':'Ambition','shar1_1':'SharedInterest','When':'When'})
df21.columns=df21.columns.map({'attr7_2':'Attractiveness','sinc7_2':'Sincerity','intel7_2':'Intelligence','fun7_2':'Fun','amb7_2':'Ambition','shar7_2':'SharedInterest','When':'When'})
df_selected1=pd.concat([df11,df21],axis=0)
df_selected1.head()

,Attractiveness,Sincerity,Intelligence,Fun,Ambition,SharedInterest,When
4030,20.0,10.0,20.0,35.0,5.0,10.0,Projected
4031,20.0,10.0,20.0,35.0,5.0,10.0,Projected
4032,20.0,10.0,20.0,35.0,5.0,10.0,Projected
4033,20.0,10.0,20.0,35.0,5.0,10.0,Projected
4034,20.0,10.0,20.0,35.0,5.0,10.0,Projected

In [48]:
df_real=dataset_wave.dropna(subset=['dec','attr','sinc','intel','fun','amb','shar']).groupby('dec').mean(numeric_only=True).loc[:,'attr':'shar'].round(2).T
df_real.columns=df_real.columns.map({0:'No',1:'Yes'})
df_real.columns.name='Decision'
df_real.index=df_real.index.map({'attr':'Attractiveness','sinc':'Sincerity','intel':'Intelligence','fun':'Fun','amb':'Ambition','shar':'SharedInterest'})

df_real

Decision          No   Yes
Attractiveness  5.34  7.22
Sincerity       6.81  7.55
Intelligence    7.04  7.71
Fun             5.67  7.30
Ambition        6.45  7.10
SharedInterest  4.65  6.43

In [49]:
df_diff=df_real.loc[:,'Yes']-df_real.loc[:,'No']
df_diff.name='Difference'
df_diff

Attractiveness    1.88
Sincerity         0.74
Intelligence      0.67
Fun               1.63
Ambition          0.65
SharedInterest    1.78
Name: Difference, dtype: float64

In [50]:
fig4=px.bar(df_real,barmode='group',range_y=[0,10],width=800,title='Fig 4 : Influence of Preferences Partner on Decision',color_discrete_sequence = px.colors.qualitative.Pastel1)

fig4.update_layout(
    xaxis_title='Attributes',
    yaxis_title='Average Rating',
        legend_bordercolor="lightgrey",
    legend_borderwidth=1,
    legend_x=0.88,
    legend_y=1,
    title_x= 0.5)
fig4.add_trace(go.Scatter(x=df_diff.index,y=df_diff,name='Diff',marker_size=15,marker_symbol='square',marker_color="green"))
fig4.show()

In [51]:
fig5=px.box(df_selected1,range_y=[0,100],width=700,title='Fig 5 : Projected vs Revised Attributes',color='When',color_discrete_sequence = px.colors.qualitative.Pastel1)
fig5.update_layout(
    xaxis_title='Attributes',
    yaxis_title='Rating',
    title_x= 0.5,
    legend_bordercolor="lightgrey",
    legend_borderwidth=1,
    legend_x=0.8,
    legend_y=0.9,
    legend_title='Look For:')
fig5.show()

**Interpretation**

Figure 5 shows us that attractiveness is the most desired attribute among partners before speed dating, but it's also the most widely dispersed, showing heterogeneous opinions on it.
It is also the criterion that receives the most additional points after the date, showing that it is the most under-rated criterion.


Moreover, figure 4 shows us that participants tend to give higher ratings to attractiveness, fun and shared interests for the partner with whom they have decided to continue after the date. This confirms that actractiveness is a key criterion in the possibility of two partners matching and continuing to a second speed dating.

## Are shared interests more important than a shared racial background?

In [52]:
check_features(['match','int_corr','imprace','samerace'])

'COUNT :'

wave,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21
match,200,608,200,648,190,50,512,200,800,162,882,392,180,720,684,96,280,72,450,84,968
int_corr,200,576,160,648,190,40,512,200,800,162,882,392,140,684,684,96,280,72,450,84,968
imprace,200,592,180,648,190,45,512,200,800,162,882,392,160,702,684,96,280,72,450,84,968
samerace,200,608,200,648,190,50,512,200,800,162,882,392,180,720,684,96,280,72,450,84,968

'MAX :'

wave,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21
match,1.00,1.00,1.0,1.0,1.00,1.00,1.00,1.00,1.0,1.00,1.00,1.0,1.00,1.0,1.00,1.00,1.00,1.00,1.00,1.00,1.00
int_corr,0.73,0.83,0.8,0.9,0.85,0.52,0.85,0.71,0.9,0.81,0.88,0.8,0.75,0.8,0.85,0.72,0.78,0.61,0.91,0.74,0.84
imprace,9.00,10.00,10.0,8.0,10.00,10.00,9.00,10.00,10.0,10.00,10.00,10.0,8.00,10.0,10.00,8.00,9.00,9.00,8.00,9.00,9.00
samerace,1.00,1.00,1.0,1.0,1.00,1.00,1.00,1.00,1.0,1.00,1.00,1.0,1.00,1.0,1.00,1.00,1.00,1.00,1.00,1.00,1.00

'MIN :'

wave,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21
match,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00
int_corr,-0.51,-0.61,-0.63,-0.57,-0.5,-0.51,-0.63,-0.47,-0.83,-0.63,-0.7,-0.62,-0.52,-0.52,-0.62,-0.55,-0.46,-0.44,-0.3,-0.46,-0.73
imprace,1.00,1.00,1.00,1.00,1.0,1.00,1.00,1.00,1.00,1.00,1.0,1.00,1.00,1.00,1.00,0.00,1.00,1.00,1.0,1.00,1.00
samerace,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00

'NULL:'

           0         1        2         3
index  match  int_corr  imprace  samerace
0          0       158       79         0

In [53]:
df_share1=dataset.dropna(subset=['match','int_corr','imprace','samerace']).groupby('match')[['int_corr','imprace']].mean().round(2)
df_share1.index=df_share1.index.map({0:'No',1:'Yes'})
df_share1.columns=df_share1.columns.map({'int_corr':'Correlation Interest','samerace':'Same Race','imprace':'Same race Importance'})
df_share1=df_share1.T
df_share1

match                   No   Yes
Correlation Interest  0.19  0.22
Same race Importance  3.85  3.46

In [54]:
df_share11=dataset.dropna(subset=['match','int_corr','imprace']).loc[:,['int_corr','imprace','match']]
df_share11['match']=df_share11['match'].map({0:'No',1:'Yes'})
df_share11.head()

   int_corr  imprace match
0      0.14      2.0    No
1      0.54      2.0    No
2      0.16      2.0   Yes
3      0.61      2.0   Yes
4      0.21      2.0   Yes

In [55]:

df_share2=dataset.dropna(subset=['match','int_corr','imprace']).groupby('match')['samerace'].value_counts(normalize=True).reset_index(name='Proportion').set_index('match')
df_share2.index=df_share2.index.map({0:'No',1:'Yes'})
df_share2.loc[:,'samerace']=df_share2.loc[:,'samerace'].map({0:'No',1:'Yes'})
df_share2.loc[:,'Proportion']=df_share2.loc[:,'Proportion'].map(lambda x: round(x*100,0))
df_share2

/tmp/ipykernel_2308675/2535816685.py:3: FutureWarning:

Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['No' 'Yes' 'No' 'Yes']' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.

      samerace  Proportion
match
No          No        60.0
No         Yes        40.0
Yes         No        58.0
Yes        Yes        42.0

In [56]:
fig6 = make_subplots(rows=1, cols=2,subplot_titles=('Correlation Interest','Same Race Importance'))

fig61=px.box(df_share11,x='match',y='int_corr', range_y=[0,1],width=500,color='match',color_discrete_sequence = px.colors.qualitative.Set2)

fig62=px.box(df_share11,range_y=[0,10],x='match',y='imprace',width=500,color='match',color_discrete_sequence = px.colors.qualitative.Set2)

for trace in fig61.data:
    fig6.add_trace(trace, row=1, col=1)

for trace in fig62.data:
    fig6.add_trace(trace, row=1, col=2)

fig6.update_layout(
    height=600,
    width=1000,
    title_text="Fig 6 : Disribution of Interests Correlation and Race Importance by Match ",
    title_x=0.5,
    xaxis_title="Match",
    xaxis2_title="Match",
    yaxis_title="Coeff. Corr.",
    yaxis2_title="Rating",
    legend_title="Match",
    legend_visible=False


    )
fig6.show()

In [57]:
fig7=px.bar(df_share2,y='Proportion',color='samerace', title='Fig 7 : Race Share Distribution by Match',color_discrete_sequence = px.colors.qualitative.Set2)
fig7.update_layout(
    title_x= 0.5,
    width=500,
    legend_title= 'Get Same Race :',
    yaxis_title='Distribution',
    xaxis_title='Match',
    yaxis_ticksuffix='%'
    )
fig7.show()

**Interpretation**

Figure 6 shows us that the correlation of common interests between partners does not significantly impact the possibility of a match.
We also see that the importance of having the same race does not significantly impact the match, however we see that people who have given a rating between 5 and 6 may see their chance of entering a match reduced.
Figure 7 also confirms that the proportion of participants having the same race or not is identical whether the participants have matched or not. which confirms to us that having the same race is not an essential criterion in the possibility of matching.

In conclusion, whether participants share the same race or the same interests does not significantly affect their chances of matching.

# Can people accurately predict their own perceived value in the dating market?

In [58]:
check_features(['attr_o','sinc_o','intel_o','fun_o','amb_o','attr3_1','sinc3_1','intel3_1','fun3_1','amb3_1'])

'COUNT :'

wave,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21
attr_o,199,601,188,647,175,50,510,195,799,162,879,391,178,653,661,95,280,72,444,84,903
sinc_o,200,590,187,641,175,47,511,190,790,162,861,391,169,652,657,95,279,68,444,82,900
intel_o,200,586,186,647,175,45,507,191,789,160,860,381,178,645,652,95,278,66,444,84,903
fun_o,200,587,186,622,173,48,500,190,769,160,866,385,178,645,645,95,278,66,444,82,899
amb_o,198,574,179,580,173,47,451,175,761,146,819,374,162,628,585,93,278,68,425,78,862
attr3_1,200,592,180,648,190,45,512,200,800,162,882,392,160,702,666,88,280,72,450,84,968
sinc3_1,200,592,180,648,190,45,512,200,800,162,882,392,160,702,666,88,280,72,450,84,968
intel3_1,200,592,180,648,190,45,512,200,800,162,882,392,160,702,666,88,280,72,450,84,968
fun3_1,200,592,180,648,190,45,512,200,800,162,882,392,160,702,666,88,280,72,450,84,968
amb3_1,200,592,180,648,190,45,512,200,800,162,882,392,160,702,666,88,280,72,450,84,968

'MAX :'

wave,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21
attr_o,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.5,10.0,10.0,9.0,10.0,9.0,10.0
sinc_o,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0
intel_o,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0
fun_o,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,9.0,11.0,10.0,10.0,10.0,10.0
amb_o,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0
attr3_1,10.0,8.0,10.0,10.0,9.0,9.0,10.0,10.0,10.0,10.0,10.0,9.0,9.0,10.0,9.0,9.0,9.0,10.0,10.0,9.0,10.0
sinc3_1,9.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0
intel3_1,10.0,10.0,10.0,10.0,10.0,9.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0
fun3_1,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,9.0,10.0,10.0,9.0,10.0,9.0,10.0,10.0,10.0
amb3_1,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,9.0,10.0,10.0,10.0,10.0,10.0

'MIN :'

wave,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21
attr_o,1.0,1.0,0.0,0.0,1.0,3.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
sinc_o,1.0,1.0,1.0,0.0,1.0,5.0,3.0,3.0,1.0,2.0,0.0,0.0,2.0,1.0,0.0,2.0,0.0,2.0,0.0,1.0,0.0
intel_o,1.0,1.0,0.0,0.0,2.0,4.0,3.0,3.0,1.0,4.0,1.0,2.0,3.0,2.0,0.0,4.0,3.0,3.0,0.0,3.0,0.0
fun_o,1.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,2.0,0.0,0.0,1.0,0.0,0.0,1.0,2.0,1.0,0.0,1.0,0.0
amb_o,1.0,1.0,1.0,0.0,0.0,4.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,2.0,0.0,2.0,2.0,1.0,0.0,4.0,0.0
attr3_1,4.0,3.0,5.0,3.0,2.0,6.0,5.0,4.0,4.0,3.0,3.0,5.0,5.0,4.0,4.0,6.0,2.0,4.0,3.0,5.0,3.0
sinc3_1,3.0,2.0,6.0,5.0,6.0,7.0,5.0,5.0,5.0,6.0,4.0,3.0,4.0,2.0,5.0,7.0,4.0,5.0,7.0,5.0,4.0
intel3_1,6.0,7.0,7.0,5.0,6.0,8.0,5.0,7.0,6.0,3.0,7.0,7.0,6.0,6.0,6.0,6.0,4.0,5.0,6.0,8.0,5.0
fun3_1,5.0,2.0,5.0,3.0,4.0,7.0,5.0,4.0,3.0,2.0,5.0,6.0,5.0,2.0,4.0,4.0,4.0,5.0,2.0,4.0,3.0
amb3_1,3.0,2.0,5.0,2.0,6.0,6.0,2.0,5.0,3.0,4.0,3.0,3.0,3.0,3.0,5.0,3.0,4.0,2.0,5.0,4.0,4.0

'NULL:'

,0,1,2,3,4,5,6,7,8,9
index,attr_o,sinc_o,intel_o,fun_o,amb_o,attr3_1,sinc3_1,intel3_1,fun3_1,amb3_1
0,212,287,306,360,722,105,105,105,105,105

In [59]:
name_index=['Attractive','Sincere','Intelligent','Fun','Ambitious']
name_col=['Estimate','Real','Diff']

do=dataset.dropna(subset=['attr_o','sinc_o','intel_o','fun_o','amb_o']).loc[:,'attr_o':'amb_o'].median()
do.index=name_index
d1=dataset.dropna(subset=['attr3_1','sinc3_1','intel3_1','fun3_1','amb3_1']).loc[:,'attr3_1':'amb3_1'].median()

d1.index=name_index

df_predict=pd.concat([d1,do,(d1-do)],axis=1)
df_predict.columns=name_col
df_predict

             Estimate  Real  Diff
Attractive        7.0   6.0   1.0
Sincere           8.0   7.0   1.0
Intelligent       8.0   7.0   1.0
Fun               8.0   7.0   1.0
Ambitious         8.0   7.0   1.0

In [60]:
fig8=px.bar(df_predict.iloc[:,[0,1]],barmode='group',range_y=[-10,10],width=900,title='Fig 8 : Ratings of partner after Dating vs Own Estimate',color_discrete_sequence = px.colors.qualitative.Plotly)

fig8.update_layout(
    xaxis_title=None,
    yaxis_title='Average Rating',
    legend_title=None,
    title_x= 0.5)
fig8.add_trace(go.Scatter(x=df_predict.index,y=df_predict.iloc[:,2],name='Over vs Under Est.',marker_size=15,marker_symbol='square',marker_color="green"))
fig8.show()

**Interpretation**

If we compare the ratings given by a participant's partner with the ratings they give themselves for all preferences. Figure 8 shows us that, on average across all attributes, participants over-rate by 1 point their own perceived value in the dating market

# In terms of getting a second date, is it better to be someone's first speed date of the night or their last?

In [61]:
check_features(['order','round','match','date_3','numdat_3','num_in_3'])

'COUNT :'

wave,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21
order,200,608,200,648,190,50,512,200,800,162,882,392,180,720,684,96,280,72,450,84,968
round,200,608,200,648,190,50,512,200,800,162,882,392,180,720,684,96,280,72,450,84,968
match,200,608,200,648,190,50,512,200,800,162,882,392,180,720,684,96,280,72,450,84,968
date_3,100,293,90,432,100,25,288,150,480,126,399,210,66,206,296,38,110,30,135,26,374
numdat_3,0,0,0,0,0,10,176,30,220,72,294,84,19,112,129,16,86,12,60,0,176
num_in_3,0,32,10,54,30,5,32,0,40,0,105,42,9,56,56,0,42,0,45,0,110

'MAX :'

wave,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21
order,10.0,19.0,10.0,18.0,10.0,5.0,16.0,10.0,20.0,9.0,21.0,14.0,10.0,20.0,19.0,8.0,14.0,6.0,15.0,7.0,22.0
round,10.0,19.0,10.0,18.0,10.0,5.0,16.0,10.0,20.0,9.0,21.0,14.0,10.0,20.0,19.0,8.0,14.0,6.0,15.0,7.0,22.0
match,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
date_3,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0
numdat_3,NaN,NaN,NaN,NaN,NaN,1.0,2.0,1.0,3.0,3.0,9.0,1.0,1.0,1.0,1.0,1.0,2.0,0.0,1.0,NaN,1.0
num_in_3,NaN,0.0,0.0,4.0,1.0,0.0,1.0,NaN,1.0,NaN,2.0,1.0,1.0,1.0,2.0,NaN,1.0,NaN,1.0,NaN,2.0

'MIN :'

wave,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21
order,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
round,10.0,16.0,10.0,18.0,10.0,5.0,16.0,10.0,20.0,9.0,21.0,14.0,9.0,18.0,18.0,6.0,11.0,6.0,15.0,6.0,22.0
match,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
date_3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
numdat_3,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,NaN,0.0
num_in_3,NaN,0.0,0.0,0.0,0.0,0.0,1.0,NaN,0.0,NaN,0.0,1.0,1.0,1.0,0.0,NaN,0.0,NaN,1.0,NaN,1.0

'NULL:'

           0      1      2       3         4         5
index  order  round  match  date_3  numdat_3  num_in_3
0          0      0      0    4404      6882      7710

In [62]:
data_order=dataset[['order','match','date_3']].dropna(subset=['order','match','date_3'])

In [63]:
df_first=data_order.groupby(['order'])['match'].mean().reset_index(drop=False).round(2)
df_first.columns=['Order','Match']
df_first1=data_order.groupby(['order'])['date_3'].mean().reset_index(drop=False).round(2)
df_first1.columns=['Order','Second_Date_Over_All']

In [64]:
fig9=px.scatter(df_first,x='Order',y='Match',range_y=[0,1],width=900,title='Fig 9 : Average match by Order of the Date during the Night',trendline='ols',trendline_color_override='red')
fig9.update_layout(
    xaxis_title='Order of the date',
    yaxis_title='Average Match',
    title_x= 0.5)
fig9.show()

In [ ]:
fig10=px.scatter(df_first1,x='Order',y='Second_Date_Over_All',range_y=[0,1],width=900,title='Fig 10 : Average Second Date Over All by Order of the Date during the Night',trendline='ols',trendline_color_override='red')
fig10.update_layout(
    xaxis_title='Order of the date',
    yaxis_title='Average Second Date Over All',
    title_x= 0.5)
fig10.show()

In [ ]:
data_order1=dataset[['order','match','date_3','round']].dropna(subset=['order','match','date_3']).sort_values(by='round')
data_order1['round']=data_order1['round'].map(lambda x : str(x))

In [ ]:
fig11=px.scatter(data_order1,x='order',y='match',color='round',range_y=[0,1],width=900,title='Fig 11 : Average Match by Order during the night and by number of round',trendline='ols',trendline_color_override='red')
fig11.update_layout(
    xaxis_title='Order of the date',
    yaxis_title='Average Match',
    legend_title='Number of round',
    title_x= 0.5)
fig11.update_traces(marker=dict(color='blue'))
fig11.update_xaxes(showgrid=True, gridwidth=1, gridcolor='lightgray')
fig11.update_yaxes(showgrid=True, gridwidth=1, gridcolor='lightgray')

fig11.update_traces(marker=dict(opacity=0))


fig11.show()

**Interpretation**

Figure 9 shows that the average number of matches is not significantly affected by the order of the date during the evening. However, figure 11 also shows us that the more rounds there are in the evening and the later the date, the average number of matches between participants tends to decrease slightly.

Conversely, if we take as a reference the number of second dates that took place on all waves for a participant, figure 10 shows us that the later the date, the higher the average number of second dates is. However, this is biased, since the second date did not necessarily take place at the end of the event.

If we refer to this last graph, we can say : It's better to be someone's last speed date of the night due to get a second date.